# Generated by Django 5.0.6 on 2024-07-07 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='content',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='advertiser',
            old_name='advertiser_name',
            new_name='name',
        ),
    ]
