# Generated by Django 5.0.6 on 2024-07-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0002_rename_content_ad_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='landing_url',
            field=models.URLField(null=True),
        ),
    ]
