# Generated by Django 5.0.6 on 2024-07-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0004_remove_ad_click_remove_ad_views_ad_approve_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='cpc',
            field=models.IntegerField(default=5),
        ),
    ]
